- name: Install mysql-server
  apt:
    name: mysql-server
    state: latest

- name: Install mysql-client
  apt:
    name: mysql-client
    state: latest

- name: Make sure pymysql is present
  become: true # needed if the other tasks are not played as root
  pip:
    name: pymysql
    state: present

- name: update mysql root password for all root accounts
  become: true
  no_log: false
  mysql_user:
    name: root
    host: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: actual_root_mysql_password
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
    state: present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
