- name: disable apache2
  service:
    name: apache2
    state: stopped
    enabled: no

- name: Install nginx
  apt:
    name: nginx
    state: latest

- name: push NGINX default host conf
  copy: src=templates/nginx-default-host dest=/etc/nginx/sites-available/default mode=0640

- name: reload nginx
  service:
    name: nginx
    state: reloaded
