- name: install php repo
  shell: apt install software-properties-common && add-apt-repository ppa:ondrej/php -y && apt update

###- name: install php 8.1
###  shell: apt install php8.1 php8.1-cli php8.1-fpm php8.1-bcmath php8.1-common php8.1-gd php8.1-imap php8.1-ldap php8.1-mbstring php8.1-mcrypt php8.1-mysql php8.1-pdo php8.1-soap php8.1-tidy php8.1-xml php8.1-xmlrpc

- name: install php 8.1
  apt:
    name: php8.1
    state: present
    update_cache: yes

- name: install php 8.1 fpm
  apt:
    name: php8.1-fpm  
    state: present   
    update_cache: yes

- name: install php 8.1 bcmath
  apt:
    name: php8.1-bcmath
    state: present
    update_cache: yes

- name: install php8.1-common
  apt:
    name: php8.1-common
    state: present
    update_cache: yes

- name: install php8.1-gd 
  apt:
    name: php8.1-gd
    state: present
    update_cache: yes

- name: install php8.1-imap    
  apt:
    name: php8.1-imap    
    state: present   
    update_cache: yes

- name: install php8.1-ldap    
  apt:
    name: php8.1-ldap    
    state: present   
    update_cache: yes

- name: install php8.1-mbstring
  apt:
    name: php8.1-mbstring
    state: present   
    update_cache: yes

- name: install php8.1-mcrypt
  apt:
    name: php8.1-mcrypt
    state: present   
    update_cache: yes

- name: install php8.1-mysql
  apt:
    name: php8.1-mysql
    state: present   
    update_cache: yes

- name: install php8.1-pdo
  apt:
    name: php8.1-pdo
    state: present   
    update_cache: yes

- name: install php8.1-soap
  apt:
    name: php8.1-soap
    state: present   
    update_cache: yes

- name: install php8.1-tidy
  apt:
    name: php8.1-tidy
    state: present   
    update_cache: yes

- name: install php8.1-xml
  apt:
    name: php8.1-xml
    state: present   
    update_cache: yes

- name: install php8.1-xmlrpc
  apt:
    name: php8.1-xmlrpc
    state: present   
    update_cache: yes
